### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by alexanderedge**
This includes a bump to node-apn which accepts the new `mutable-content` payload field.

### CODE REVIEW

**Comment by flovilmart** [comment]
Could you add the changelog? Last question, is it forward and backwards compatible with parse-server? Is there anything that needs to be done there to enable this new feature?

**Comment by alexanderedge** [comment]
Where is the existing changelog? Do you want me to start a new one?

This isn't a breaking change, but it is an addition to the notifications API hence the minor version bump.

Users simply have to add `"mutable-content" : 1` to the `data` property in `Parse.Push.send()`. I will make a PR to update the docs on parse-server once this is closed.

**Comment by flovilmart** [comment]
Yeah, we could start one starting that version, that would be nice!

For the rest, awesome man! Thanks, that will land just in time for iOS 10 :)

**Comment by alexanderedge** [comment]
I can't generate a changelog for `1.1.0` yet as it isn't tagged. Once you merge this PR and tag the release then github_changelog_generator will be able to pick up the changes. I can do this in a separate PR.

**Comment by flovilmart** [comment]
There is an option in github_ghangelog_generator for future tags :)

**Comment by alexanderedge** [comment]
Very useful! I've updated the changelog, thanks.

**Comment by flovilmart** [comment]
Awesome! Thanks!

**Pull request merged**
