### PR TITLE
Add support for Windows Notification Service

### PR DESCRIPTION
**Pull request by sherry0319**
Add support for Windows Notification Service via https://github.com/tjanczuk/wns.
Config of parse-server add :
"push": {
                "wp": {
                "clientID": "ms-app://... Enter your app client ID here",
                "clientSecret": "Enter your app secret key here",
                "accessTokenPath": "/home/accessToken.pem" the file path to dump the accessToken to make push after.
                }
        }

The param "deviceToken" of _Installation means the push uri of the windows phone device.
More details on https://msdn.microsoft.com/en-us/library/windows/apps/hh465435.aspx

### CODE REVIEW

**Comment by ramonornela** [comment]
+1 support WP

**Comment by flovilmart** [comment]
This has failures and needs rebase.

**Comment by parseserverpush** [comment]
Can you support WindownPhone ?

**Comment by parseserverpush** [comment]
@sherry0319 I do not understand config "accessTokenPath". How I can find it. Thanks u

**Comment by sherry0319** [comment]
Windows Store notication service need an access token which you can get from windows access token server. See https://msdn.microsoft.com/en-us//library/windows/apps/xaml/hh868245.aspx for more details.
Because microsoft said the user should better save the access token in local until it has expired rather than request from server in every push handle, so I will dump the access token to "accessTokenPath". You just have to give a path which your node.js service have write permission to this file. It will read the file for access token first, and request from windows server when some error occured then save it to "accessTokenPath".




At 2016-11-10 10:20:01, "parseserverpush" <notifications@github.com> wrote:


@sherry0319 I do not understand config "accessTokenPath". How I can find it. Thanks u

**Comment by sherry0319** [comment]
I wish I cound. But node.js or javascript are not very familiar to me, so I don't known why it doesn't work. And I have no spare time currently to learn how to make it right.
I wrote a php version windows phone notification system instead and it works well.
Sorry for not finish the support.

At 2016-11-07 23:22:51, "parseserverpush" <notifications@github.com> wrote:


Can you support WindownPhone ?

**Comment by parseserverpush** [comment]
Thanks you.

**Comment by parseserverpush** [comment]
I sended notify successfull but it only send 1 device / request. i want push notification multiple devices in one request. like Android or IOS, where i can send notification to ~1000 devices per request. That's pretty easier. please let me now. thanks u.

**Pull request closed without merging**
